version: '3.8'

services:
  server:
    container_name: shorty_grpc
    build: ./
    ports:
      - 5001:5000
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    container_name: shorty_redis
    restart: always
    image: redis:alpine
    ports:
      - 6000:6379
