version: '3.8'

services:
    server:
        container_name: server
        build: ./
        context: .
         dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        env_file:
            - ./.env.dev
    client:
        container_name: server
        build: ./
        context: .
         dockerfile: ./Dockerfile-client
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
    redis:
        restart: always
        image: redis:alpine
        ports:
            - 6379:6379