version: '3.8'

services:
  server:
    build: ./
    command: ./server
    ports:
      - 5001:5000
    depends_on:
      - redis
    env_file: 
      - .env

  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6000:6379
