version: '2.4'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379